/**
 * Runtime Flags — in-memory flag overrides without restart.
 *
 * Flow:
 * 1. Load: .env.local overrides .env defaults
 * 2. Get/Set: in-memory Map, checked before process.env
 * 3. /setphase command: updates in-memory + writes .env.local
 * 4. Other modules: import { runtimeFlags } from this file
 *
 * Usage in other modules:
 *   import { runtimeFlags } from '../util/runtime-flags';
 *   if (runtimeFlags.get('PHASE_PROBLEM_DEF') === 'active') { ... }
 */

import fs from 'fs';
import path from 'path';

const ENV_LOCAL_PATH = path.join(process.cwd(), '.env.local');

// In-memory overrides — checked first
const _overrides = new Map<string, string>();

// ── Load ────────────────────────────────────────────────────────────────────

/**
 * Load overrides from .env.local file (key=value per line, # for comments).
 * Called at startup.
 */
export function loadRuntimeOverrides(): void {
  if (!fs.existsSync(ENV_LOCAL_PATH)) return;

  const lines = fs.readFileSync(ENV_LOCAL_PATH, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx < 0) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    _overrides.set(key, value);
  }
}

/**
 * Persist current overrides to .env.local file.
 */
function saveOverrides(): void {
  const entries = Array.from(_overrides.entries());
  const lines = ['# Runtime overrides — generated by /setphase command', ''];
  for (const [key, value] of entries) {
    lines.push(`${key}=${value}`);
  }
  fs.writeFileSync(ENV_LOCAL_PATH, lines.join('\n') + '\n');
}

// ── Access ─────────────────────────────────────────────────────────────────

/**
 * Get a runtime flag value.
 * Checks: in-memory overrides → .env.local file → process.env → defaultValue
 */
export function getRuntimeFlag(key: string, defaultValue?: string): string {
  if (_overrides.has(key)) return _overrides.get(key)!;
  if (process.env[key]) return process.env[key]!;
  return defaultValue ?? 'disabled';
}

/**
 * Set a runtime flag in memory and persist to .env.local.
 */
export function setRuntimeFlag(key: string, value: string): void {
  _overrides.set(key, value);
  saveOverrides();
  console.log(`[RuntimeFlags] ${key}=${value} (persisted to .env.local)`);
}

/**
 * List all current flag values (for /phase status).
 */
export function listRuntimeFlags(): Record<string, string> {
  return {
    PHASE_SUB_PROBLEMS: getRuntimeFlag('PHASE_SUB_PROBLEMS', 'disabled'),
    PHASE_PROBLEM_DEF: getRuntimeFlag('PHASE_PROBLEM_DEF', 'disabled'),
    PHASE_CROSS_LINK: getRuntimeFlag('PHASE_CROSS_LINK', 'disabled'),
    PHASE_ITERATION: getRuntimeFlag('PHASE_ITERATION', 'disabled'),
    PHASE_RICH_SYNTHESIS: getRuntimeFlag('PHASE_RICH_SYNTHESIS', 'disabled'),
    PHASE_MEETING_PREP: getRuntimeFlag('PHASE_MEETING_PREP', 'disabled'),
    PHASE_MEETING: getRuntimeFlag('PHASE_MEETING', 'disabled'),
    PHASE_AUTO_UPDATE: getRuntimeFlag('PHASE_AUTO_UPDATE', 'disabled'),
  };
}

// Load overrides at module import time
loadRuntimeOverrides();
