/**
 * AI Help Assistant — interprets natural language and explains Zolara features
 * Uses MiniMax to understand non-specific commands and provide contextual help
 */

import { llm } from '../engine/llm/minimax';
import { db } from '../data/db';
import { projects, admins, members } from '../data/schema/projects';
import { eq } from 'drizzle-orm';
import { redis } from '../data/redis';

// ── System Prompt ─────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are Zolara's assistant running inside the @Zolara_bot. Your role is to help admins and members understand and use Zolara.

Zolara is a consensus engine product that helps teams reach alignment on problems through structured rounds.

## CORE CONCEPTS

### Rounds
A "round" is a structured consensus cycle where team members:
1. Are asked a question about a chosen topic
2. Submit their perspective (private, not visible to others during the round)
3. After all submit, a synthesis report is generated by AI
4. Report is posted to the team group for reactions
5. Reactions are tracked

### Projects
- An admin creates a project (gives it a name and optionally a description)
- Each project gets its own bot via Telegram's BotFather (Managed Bots API)
- Members join via invite links or by the admin adding them
- Multiple admins can manage a project

### Admin Commands
- /create — start project creation flow
- /startround — start validation for a new consensus round topic
- /refinetopic — submit a clearer topic after validation returns needs_work
- /adminguide or /admin-guide — show the admin guide and current refinement next step
- /next — show the one best next admin action for the current project
- /nudge — remind pending onboarding members or members missing active-round responses
- /cancelround — cancel the current round
- /projects — view and manage your projects
- /members — list members in current project
- /invite — get an invite link for members
- /status — check current round status
- /admins — list project admins
- /addadmin — add a new admin by Telegram handle
- /removeadmin — remove an admin
- /transferownership — transfer project ownership
- /settings — configure project settings
- /setphase — toggle experimental phases

### Member Flow
1. /start → claim commitment with invite code
2. Onboarding: enter name, role, expertise areas
3. Answer questions when a round is active
4. React to synthesis reports in the group

### Key Terms
- "perspective" = a member's answer to a round question
- "synthesis report" = AI-generated summary of all perspectives
- "engagement events" = reactions, submissions, completions tracked for analytics

## CAPABILITIES
- Explain any Zolara feature or process
- Help navigate admin commands
- Explain the member onboarding flow
- Clarify what a round means and how it works
- Explain project context (who's the admin, what's the current round status)

## STYLE
- Be direct and helpful, not verbose
- Use bullet points for clarity
- When asked "how do I...", give step-by-step
- When asked "what is...", give a concise definition
- When unclear, ask a clarifying question

Never make up features that don't exist. If you don't know something, say so.`;

interface HelpContext {
  isAdmin: boolean;
  adminProjects: Array<{ id: string; name: string; status: string }>;
  memberProjects: Array<{ id: string; name: string }>;
  currentProjectName?: string;
  currentRoundStatus?: string;
  isInFlow: boolean;
  flowName?: string;
}

/**
 * Gather contextual information about the user for richer AI responses
 */
async function gatherContext(userId: number): Promise<HelpContext> {
  const adminProjects: Array<{ id: string; name: string; status: string }> = [];

  // Check if admin
  const adminRows = await db.select({ id: admins.id }).from(admins).where(eq(admins.telegramId, userId));
  const isAdmin = adminRows.length > 0;

  if (isAdmin) {
    const adminId = adminRows[0].id;
    const rows = await db
      .select({ id: projects.id, name: projects.name, status: projects.status })
      .from(projects)
      .where(eq(projects.adminId, adminId));
    adminProjects.push(...rows.map(r => ({
      id: r.id,
      name: r.name ?? 'Unknown',
      status: r.status ?? 'unknown',
    })));
  }

  // Check active flows (initiation, claim, onboarding)
  const initState = await redis.get(`init:${userId}`);
  const claimState = await redis.get(`claim:${userId}`);
  const onboardState = await redis.get(`onboard:${userId}`);

  let isInFlow = false;
  let flowName: string | undefined;
  if (initState) { isInFlow = true; flowName = 'project creation'; }
  else if (claimState) { isInFlow = true; flowName = 'member claim'; }
  else if (onboardState) { isInFlow = true; flowName = 'member onboarding'; }

  // Current selected project (from Redis)
  const selectedProjectId = await redis.get(`selected_project:${userId}`);
  let currentProjectName: string | undefined;

  if (selectedProjectId) {
    const [proj] = await db
      .select({ name: projects.name })
      .from(projects)
      .where(eq(projects.id, selectedProjectId))
      .limit(1);
    if (proj) currentProjectName = proj.name ?? undefined;
  }

  return { isAdmin, adminProjects, memberProjects: [], currentProjectName, currentRoundStatus: undefined, isInFlow, flowName };
}

/**
 * Build a rich context string for the AI
 */
function buildContextString(ctx: HelpContext): string {
  let s = '';
  if (ctx.isAdmin) {
    s += `You are an admin with ${ctx.adminProjects.length} project(s):\n`;
    ctx.adminProjects.forEach(p => { s += `  - ${p.name} (${p.status})\n`; });
  }
  if (ctx.memberProjects.length > 0) {
    s += `You are a member of: ${ctx.memberProjects.map(p => p.name).join(', ')}\n`;
  }
  if (ctx.currentProjectName) {
    s += `Current project: ${ctx.currentProjectName}\n`;
  }
  if (ctx.isInFlow) {
    s += `You are currently in a "${ctx.flowName}" flow.\n`;
  }
  return s || 'No specific project context.';
}

/**
 * Handle an AI help/interpretation request
 * Called when a non-command message doesn't match any known flow
 */
export async function handleAIHelp(ctx: any, userId: number, userMessage: string): Promise<void> {
  // Don't respond to very short messages
  if (userMessage.trim().length < 3) return;

  // Don't respond to single words that look like commands
  const singleWordCommands = ['help', 'start', 'create', 'projects', 'members', 'status', 'invite', 'settings', 'help me', '?', 'what', 'how', 'who', 'where', 'why', 'when'];
  const isSingleWordHelp = singleWordCommands.includes(userMessage.trim().toLowerCase());

  try {
    const context = await gatherContext(userId);
    const contextStr = buildContextString(context);

    const fullSystem = `${SYSTEM_PROMPT}\n\n## USER CONTEXT\n${contextStr}`;

    console.log('[AI Help] calling MiniMax, message:', userMessage.substring(0, 100));
    const response = await llm.generate({
      systemPrompt: fullSystem,
      userPrompt: userMessage,
      temperature: 0.7,
      maxTokens: 800,
    });
    console.log('[AI Help] response:', response.text?.substring(0, 100));

    if (response.text) {
      await ctx.reply(response.text.trim(), { parse_mode: 'Markdown' });
    } else {
      await ctx.reply("I'm not sure how to help with that. Try using /help to see available commands, or ask a specific question about Zolara's features.");
    }
  } catch (err) {
    console.error('[AI Help] error:', err);
    await ctx.reply("I'm having trouble understanding that right now. Please try again or use /help for available commands.");
  }
}